name: drahmstrassebot
channels:
  - anaconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - beautifulsoup4=4.12.2
  - blas=1.0
  - bottleneck=1.3.5
  - bzip2=1.0.8
  - ca-certificates=2023.08.22
  - intel-openmp=2023.1.0
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - ncurses=6.4
  - numexpr=2.8.7
  - numpy=1.26.0
  - numpy-base=1.26.0
  - openssl=3.0.11
  - pandas=2.1.1
  - pip=23.3
  - python=3.11.5
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - pytz=2023.3.post1
  - readline=8.2
  - setuptools=68.0.0
  - six=1.16.0
  - soupsieve=2.5
  - sqlite=3.41.2
  - tbb=2021.8.0
  - tk=8.6.12
  - tzdata=2023c
  - wheel=0.41.2
  - xz=5.4.2
  - yaml=0.2.5
  - zlib=1.2.13
  - pip:
      - aiohttp==3.8.6
      - aiosignal==1.3.1
      - anyio==4.0.0
      - async-timeout==4.0.3
      - attrs==23.1.0
      - certifi==2023.7.22
      - charset-normalizer==3.3.1
      - frozenlist==1.4.0
      - h11==0.14.0
      - httpcore==1.0.1
      - httpx==0.25.1
      - idna==3.4
      - multidict==6.0.4
      - pyyaml==6.0.1
      - requests==2.31.0
      - sniffio==1.3.0
      - telepot==12.7
      - urllib3==2.0.7
      - yarl==1.9.2
      - youtube-search-python==1.6.6
